enum SegmentEvent {
  DOWNLOAD = 'Download',
  EXPLORE_ON_WEB = 'Explore on web',
  OPEN_SEND_TO_DESKTOP = 'Open Send To Desktop',
  MICROSOFT_STORE = 'Go to Microsoft Store',
  APP_STORE = 'Go to AppStore',
  SUBSCRIBE_TO_MOBILE = 'Subscribe To Mobile',
  GO_TO_EXPLORER = 'Go To Explorer',
  SEE_FESTIVAL_EVENTS = 'See Festival Events Schedule',
  GO_TO_EXPLORER_MVMF_LIVE_EVENT = 'Go To Explorer MVMF Live Event',
  WATCH_MORE = 'Watch More',
  YOUR_TUTORIAL = 'Your Tutorial',
  BROWSER_CREATORS = 'Browser Creators',
  ARE_YOU_CREATOR = 'Are You A Creator',
  CREATORS_CONNECT_CARD = 'Creators Connect Card',
  CREATE_YOUR_AVATAR = 'Create Your Avatar',
  MISSIONS_EXPERIENCE = 'experience',
  MISSIONS_CREATE = 'create',
  MISSIONS_INFLUENCE = 'influence',
  INVITE_HERO = 'Invite Hero',
  CLICK = 'Click',
  CLIENT_NOT_INSTALLED = 'Client not installed',
  DOWNLOAD_STARTED = 'download_started',
  DOWNLOAD_SUCCESS = 'download_success',
  DOWNLOAD_FAILED = 'download_failed',
  DOWNLOAD_FUNNEL_EXIT = 'download_funnel_exit',
  DOWNLOAD_PAGE_EXIT = 'download_page_exit',
  DOWNLOAD_SUCCESS_ARRIVED = 'download_success_arrived',
  DOWNLOAD_REDIRECT_FAILED = 'download_redirect_failed',
  LEGACY_EVENTS_REDIRECTED = 'Legacy Events Redirected',
  LEGACY_PLACES_REDIRECTED = 'Legacy Places Redirected',
  REELS_SHARE = 'Reels Share',
  REELS_COPY_LINK = 'Reels Copy Link',
  REELS_DOWNLOAD = 'Reels Download',
  REELS_JUMP_IN = 'Reels Jump In',
  REELS_SHOW_METADATA = 'Reels Show Metadata',
  REELS_HIDE_METADATA = 'Reels Hide Metadata',
  REELS_SHOW_WEARABLES = 'Reels Show Wearables',
  REELS_HIDE_WEARABLES = 'Reels Hide Wearables',
  REELS_IMAGE_NOT_FOUND = 'Reels Image Not Found',
  REELS_CLICK_WEARABLE = 'Reels Click Wearable',
  REELS_CLICK_PROFILE = 'Reels Click Profile',
  REELS_CLICK_PLACE = 'Reels Click Place',
  REELS_CLICK_DCL_LOGO = 'Reels Click Decentraland Logo',
  REELS_CLICK_THUMBNAIL = 'Reels Click Thumbnail',
  CAST_STREAMER_JOINED = 'Cast Streamer Joined',
  CAST_WATCHER_JOINED = 'Cast Watcher Joined',
  CAST_STREAM_STARTED = 'Cast Stream Started',
  CAST_STREAM_ENDED = 'Cast Stream Ended',
  CAST_PRESENTATION_SHARED = 'Cast Presentation Shared',
  CAST_DEVICE_CHANGED = 'Cast Device Changed',
  STORAGE_ENV_SET_SUCCESS = 'Storage Env Set Success',
  STORAGE_ENV_SET_FAILURE = 'Storage Env Set Failure',
  STORAGE_ENV_DELETE_SUCCESS = 'Storage Env Delete Success',
  STORAGE_ENV_DELETE_FAILURE = 'Storage Env Delete Failure',
  STORAGE_ENV_CLEAR_SUCCESS = 'Storage Env Clear Success',
  STORAGE_ENV_CLEAR_FAILURE = 'Storage Env Clear Failure',
  STORAGE_SCENE_SET_SUCCESS = 'Storage Scene Set Success',
  STORAGE_SCENE_SET_FAILURE = 'Storage Scene Set Failure',
  STORAGE_SCENE_DELETE_SUCCESS = 'Storage Scene Delete Success',
  STORAGE_SCENE_DELETE_FAILURE = 'Storage Scene Delete Failure',
  STORAGE_SCENE_CLEAR_SUCCESS = 'Storage Scene Clear Success',
  STORAGE_SCENE_CLEAR_FAILURE = 'Storage Scene Clear Failure',
  STORAGE_PLAYER_SET_SUCCESS = 'Storage Player Set Success',
  STORAGE_PLAYER_SET_FAILURE = 'Storage Player Set Failure',
  STORAGE_PLAYER_DELETE_SUCCESS = 'Storage Player Delete Success',
  STORAGE_PLAYER_DELETE_FAILURE = 'Storage Player Delete Failure',
  STORAGE_PLAYER_CLEAR_SUCCESS = 'Storage Player Clear Success',
  STORAGE_PLAYER_CLEAR_FAILURE = 'Storage Player Clear Failure',
  STORAGE_PLAYER_CLEAR_ALL_SUCCESS = 'Storage Player Clear All Success',
  STORAGE_PLAYER_CLEAR_ALL_FAILURE = 'Storage Player Clear All Failure',
  COMMUNITY_CLICK_JOIN = 'Click on Join',
  COMMUNITY_CLICK_REQUEST_TO_JOIN = 'Click on Request to Join',
  COMMUNITY_CLICK_CANCEL_REQUEST = 'Click on Cancel Request',
  COMMUNITY_CLICK_JUMP_IN = 'Click on Jump In',
  COMMUNITY_CLICK_SIGN_IN_TO_JOIN = 'Click on Sign In to Join',
  REPORT_PLAYER_SUBMIT_STARTED = 'Report Player Submit Started',
  REPORT_PLAYER_SUBMITTED = 'Report Player Submitted',
  REPORT_PLAYER_SUBMIT_FAILED = 'Report Player Submit Failed',
  SECTION_VIEWED = 'Section Viewed'
}

enum DownloadPlace {
  LANDING_HERO = 'landing-hero',
  LANDING_HERO_EPIC = 'landing-hero-epic',
  LANDING_HERO_PLATFORM_SWITCH = 'landing-hero-platform-switch',
  COME_HANG_OUT = 'come-hang-out',
  COME_HANG_OUT_PLATFORM_SWITCH = 'come-hang-out-platform-switch',
  JUMP_IN_ALREADY_USER = 'jump-in-already-user',
  PLAY_HERO = 'play-hero',
  PLAY_HERO_EPIC = 'play-hero-epic',
  PLAY_HERO_APP_STORE = 'play-hero-app-store',
  PLAY_HERO_GOOGLE_PLAY = 'play-hero-google-play',
  PLAY_EXPERIMENTAL_WEB = 'play-experimental-web',
  DOWNLOAD_PAGE = 'download-page',
  DOWNLOAD_SUCCESS_FOOTER = 'download-success-footer',
  CREATOR_HUB_DOWNLOAD_PAGE = 'creator-hub-download-page',
  CREATOR_HUB_SUCCESS_PAGE = 'creator-hub-success-page',
  CREATORS_HERO = 'creators-hero',
  UNKNOWN = 'unknown'
}

// Which download surface a download CTA click targets. Sent as the snake_case
// `download_target` dimension on `Click` events (including `event=Download`
// sub-typed ones) and on `download_*` funnel events so the warehouse can split
// the direct desktop-installer flow from surfaces that never reach
// `/download_success` and so must not pollute the desktop activation metric:
// the mobile store exits (App Store / Google Play) and Epic, which delivers the
// same desktop client but redirects to the Epic Games Store instead of the
// in-app download. Only `desktop_installer` clicks are expected to produce a
// `download_started` — filter the Click → download_started funnel on it.
enum DownloadTarget {
  DESKTOP_INSTALLER = 'desktop_installer',
  APP_STORE = 'app_store',
  GOOGLE_PLAY = 'google_play',
  EPIC = 'epic',
  CREATOR_HUB = 'creator_hub'
}

enum SectionViewedTrack {
  CREATORS_CONNECT = 'Creators Connect',
  CREATORS_CREATE = 'Creators Create',
  CREATORS_EARN = 'Creators Earn',
  CREATORS_HERO = 'Creators Hero',
  CREATORS_JUMP_IN = 'Creators Jump In',
  CREATORS_LEARN = 'Creators Learn',
  CREATORS_WHY = 'Creators Why',
  CREATORS_FAQS = 'Creators Faqs',
  LANDING_HERO = 'Landing Hero',
  LANDING_EVENTS_PLACES_FEED = 'Landing Events Places Feed',
  LANDING_BLOG_FEED = 'Landing Blog Feed',
  LANDING_ABOUT = 'Landing About',
  LANDING_MISSIONS = 'Landing Missions',
  LANDING_MARKETPLACE = 'Landing Marketplace',
  LANDING_TRENDING = 'Landing Trending',
  LANDING_WORLDS = 'Landing Worlds',
  LANDING_FAQS = 'Landing Faqs',
  LANDING_FOOTER = 'Landing Footer',
  DOWNLOAD = 'Download',
  CREATOR_HUB_SUCCESS_FOOTER = 'Creator Hub Success Footer',
  INVITE_FIRST_HERO = 'Referrer Invite First Hero',
  INVITE_SECOND_HERO = 'Referrer Invite Second Hero',
  INVITE_THIRD_HERO = 'Referrer Invite Third Hero',
  INVITE_FAQS = 'Referrer Invite Faqs',
  LANDING_CATCH_THE_VIBE = 'Landing Catch The Vibe',
  LANDING_COME_HANG_OUT = 'Landing Come Hang Out',
  LANDING_WEEKLY_RITUALS = 'Landing Weekly Rituals',
  LANDING_EXPLORE = 'Landing Explore',
  LANDING_FOOTER_SOCIAL = 'Landing Footer Social',
  LANDING_FOOTER_SUBSCRIBE = 'Landing Footer Subscribe',
  LANDING_FOOTER_LINK = 'Landing Footer Link',
  LANDING_NAVBAR = 'Landing Navbar',
  REELS_IMAGE = 'Reels Image',
  REELS_LIST = 'Reels List',
  REELS_NOT_FOUND = 'Reels Not Found'
}

export { DownloadPlace, DownloadTarget, SectionViewedTrack, SegmentEvent }
